// All action for yakNews

// get the users current location and and weather;
export const GET_WEATHER = 'GET_WEATHER';
export const WEATHER_ERROR = 'WEATHER_ERROR';
// get the news data for the carousel
export const GET_CAROUSEL_WORLD_NEWS = 'GET_CAROUSEL_WORLD_NEWS';
export const GET_CAROUSEL_TRENDING_NEWS = 'GET_CAROUSEL_TRENDING_NEWS';
export const GET_CAROUSEL_BUSNIESS_NEWS = 'GET_CAROUSEL_BUSNIESS_NEWS';
export const GET_CAROUSEL_FOOD_NEWS = 'GET_CAROUSEL_FOOD_NEWS';
export const GET_CAROUSEL_ART_NEWS = 'GET_CAROUSEL_ART_NEWS';
export const GET_CAROUSEL_POLITICS_NEWS = 'GET_CAROUSEL_POLITICS_NEWS';
export const GET_CAROUSEL_COUNTRY_NEWS = 'GET_CAROUSEL_COUNTRY_NEWS';
export const GET_CAROUSEL_TRAVEL_NEWS = 'GET_CAROUSEL_TRAVEL_NEWS';
export const GET_CAROUSEL_FASHION_NEWS = 'GET_CAROUSEL_FASHION_NEWS';
export const GET_CAROUSEL_TECH_NEWS = 'GET_CAROUSEL_TECH_NEWS';
export const GET_CAROUSEL_HEALTH_NEWS = 'GET_CAROUSEL_HEALTH_NEWS';
export const GET_CAROUSEL_SPORT_NEWS = 'GET_CAROUSEL_SPORT_NEWS';
export const GET_CAROUSEL_SCIENCE_NEWS = 'GET_CAROUSEL_SCIENCE_NEWS';
export const CAROUSEL_ERROR = 'CAROUSEL_ERROR';
